name: Run test when pushed code
run-name: ${{ github.actor }} is pushed!!!!!!

on: [workflow_dispatch, push]

jobs:
  run-shell:
    name: run shell
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: '3.10'
    steps:
      - name: checkout
        uses: actions/checkout@v4
      
      - name: python setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          architecture: 'x64'

      - name: run current Dir
        run: |
          ls && pwd

      - name: run shell
        run: |
          cd submodule_repo
          ls -la
          if [! -e test.sh ]; then
            exit 1
          else
            . test.sh
          fi